services:
   config:
     container_name: snow-forgeconfig
     build:
       dockerfile: Dockerfile.demo
       context: .
       args:
         - PYTHON_TAG=311
         - TAG=dev
     image: localhost/snow-forgeconfig-demo
     user: me
     volumes:
        - snow_forgeconfig_demo:/home/me/.snowflake
     env_file:
      - .env.docker
     command:
        - -f
volumes:
  snow_forgeconfig_demo:
       

