ARG PYTHON_TAG=311
FROM ghcr.io/kameshsampath/snow-dev:${PYTHON_TAG}

USER me

WORKDIR /home/me

ADD --chown=me:me src/ /home/me/app/
ADD --chown=me:me scripts/bin/run /home/me/.local/bin/run
ADD --chown=me:me scripts/bin/user_key_setup /home/me/.local/bin/user_key_setup

RUN pip install --no-cache --user jinja2 snowflake snowflake-snowpark-python
