services:
   config:
     container_name: snow-forgeconfig
     build:
       dockerfile: Dockerfile
       args:
         - BASE_IMAGE=ghcr.io/kameshsampath/snow-builder-collection/snow-base:dev
       context: .
     image: ghcr.io/kameshsampath/snow-builder-collection/snow-forgeconfig:dev
     pull_policy: always
     user: me
     volumes:
        - snow_forgeconfig:/home/me/.snowflake
     env_file:
      - .env.docker
volumes:
  snow_forgeconfig:
       

